version: "3.9"

services:
  api:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  web:
    build:
      context: ./frontend
      args:
        VITE_API_BASE: "http://api:8080"
    depends_on:
      - api
    ports:
      - "8085:80"
    restart: unless-stopped
