services:
  peptrackr:
    build: .
    container_name: peptrackr
    ports:
      - "8085:8085"
    environment:
      - DATA_DIR=/data
    volumes:
      - peptrackr_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8085/health"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  peptrackr_data:
