version: "3.9"
services:
  peptrackr:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NO_CACHE_BUSTER: "force-2025-10-24T-1"
    image: peptrackr:v17.3.2
    ports:
      - "8085:80"
    restart: unless-stopped
    volumes:
      - peptrackr_data:/data
volumes:
  peptrackr_data:
