services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: peptrackr
      POSTGRES_PASSWORD: peptrackr
      POSTGRES_DB: peptrackr
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      disable: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://peptrackr:peptrackr@db:5432/peptrackr
      NODE_ENV: production
      PORT: 8086
    depends_on:
      - db
    ports:
      - "8086:8086"
    restart: always
    healthcheck:
      disable: true

  web:
    image: peptrackr_web:portainer-300   # bump tag per deploy
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BUILD_VERSION: "portainer-300"   # bump per deploy
        CACHE_BUSTER: "300"              # bump per deploy
    depends_on:
      - backend
    ports:
      - "8085:80"
    restart: always
    healthcheck:
      disable: true

volumes:
  db_data: {}
