version: "3.9"

services:
  api:
    build:
      context: ./backend
    environment:
      API_HOST: 0.0.0.0
      API_PORT: 8080
      DATABASE_URL: sqlite:///./data.db
      CORS_ORIGINS: "*"
    volumes:
      - ./backend/data:/app
    ports:
      - "8083:8080"       # host:container → API reachable on port 8081 externally
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  web:
    build:
      context: ./frontend
      args:
        # The frontend will call the backend inside Docker by this internal name
        - VITE_API_BASE=http://api:8080
    depends_on:
      - api
    ports:
      - "8085:80"         # host:container → Web UI served on port 8085
    restart: unless-stopped

  # Optional Postgres service if you want to switch from SQLite later
  # postgres:
  #   image: postgres:16-alpine
  #   environment:
  #     POSTGRES_DB: appdb
  #     POSTGRES_USER: app
  #     POSTGRES_PASSWORD: app
  #   volumes:
  #     - dbdata:/var/lib/postgresql/data
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
  #     interval: 30s
  #     timeout: 5s
  #     retries: 5

volumes:
  dbdata:
