version: "3.9"

services:
  api:
    build:
      context: ./backend
    env_file:
      - .env
    volumes:
      - ./backend/data:/app
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  web:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE=${VITE_API_BASE}
    depends_on:
      - api
    ports:
      - "3000:80"
    restart: unless-stopped

  # postgres:
  #   image: postgres:16-alpine
  #   environment:
  #     POSTGRES_DB: appdb
  #     POSTGRES_USER: app
  #     POSTGRES_PASSWORD: app
  #   volumes:
  #     - dbdata:/var/lib/postgresql/data
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
  #     interval: 30s
  #     timeout: 5s
  #     retries: 5

volumes:
  dbdata:
