
version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: peptrackr_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: peptrackr
      POSTGRES_USER: pepuser
      POSTGRES_PASSWORD: supersecurepassword
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pepuser -d peptrackr"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: peptrackr_backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: "8086"
      DATABASE_URL: "postgresql://pepuser:supersecurepassword@db:5432/peptrackr?schema=public"
    expose:
      - "8086"
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:8086/health').then(()=>process.exit(0)).catch(()=>process.exit(1))"]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    build: ./frontend
    container_name: peptrackr_web
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "8085:80"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/ | grep -q PepTrackr || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  db_data:
